// Generated by CoffeeScript 1.6.3
(function() {
  var siteapp;

  siteapp = angular.module('siteapp', []);

  siteapp.controller('SiteController', function($scope) {
    return $scope.sites = [
      {
        title: '医疗',
        content: [
          {
            'href': 'http://www.myzx.cn/',
            'name': '名医在线',
            'category': '问答',
            'info': ''
          }, {
            'href': 'http://xingren.com/',
            'name': '杏仁医生',
            'category': '',
            'info': ''
          }
        ]
      }
    ];
  });

}).call(this);
